" Convert tabs to 4 spaces
:set tabstop=4
:set shiftwidth=4
:set expandtab

" Set modelines to on - this will respect in-file vim settings
set modeline
set modelines=5

" Color scheme
syntax enable
set background=dark

" Append modeline after last line in buffer.
" Use substitute() instead of printf() to handle '%%s' modeline in LaTeX
" files.
function! AppendModeline()
  let l:modeline = printf(" vim: set ts=%d sw=%d tw=%d %set :",
        \ &tabstop, &shiftwidth, &textwidth, &expandtab ? '' : 'no')
  let l:modeline = substitute(&commentstring, "%s", l:modeline, "")
  call append(line("$"), l:modeline)
endfunction
nnoremap <silent> <Leader>ml :call AppendModeline()<CR>

